/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab7;
import heap.Heap;
import avl.AVL;
public class Huffman {
    public static void main(String[] args) {
        
    }
}
